name: Deploy Godot Web Export

on:
  push:
    branches: [ "main" ]

jobs:
  export-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          GODOT_VERSION=4.3  # change if you're on 3.x or another 4.x release
          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mv godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot/godot

      - name: Export HTML5
        run: |
          ./godot/godot --headless --export-release "HTML5" build/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
