name: Deploy Godot HTML5 to GitHub Pages

on:
  push:
    branches: [ main ]  # deploy on push to main

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout source
        uses: actions/checkout@v5

      # 2️⃣ Export HTML5 build using firebelley/godot-export
      - name: Export Godot HTML5
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          # Pinned Godot version
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          
          relative_project_path: ./           # path to your Godot project root
          use_preset_export_path: true       # export path from export_presets.cfg
          export_preset_name: HTML5          # must match the name of your HTML5 export preset
          cache: true                        # cache Godot binaries/templates for faster CI

      # 3️⃣ Deploy exported files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages          # branch where Pages will serve files
          publish_dir: ./build              # must match your export preset output folder