name: Deploy Godot Web Export

on:
  push:
    branches: [main]

jobs:
  export-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Export HTML5 build
        uses: firebelley/godot-export@v7
        with:
          godot_executable_download_url: 'https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip'
          godot_export_templates_download_url: 'https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz'
          relative_project_path: './'
          use_preset_export_path: true
          cache: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
